### ISSUE TITLE
About the download of the video 

### ISSUE THREAD

**Issue by zxk19981227** [yhw-yhw/SHOW#11]
I want to download the video provided in the paper . But most of links to video on youtube seems invalid. Could you release or directly send me the links to download the video used in paper? I tried to download with the download_youtube.py and only download successfully with no more than 11w seconds, smaller than the 27hours described in the paper.

**Comment by lithiumice** [comment]
> I want to download the video provided in the paper . But most of links to video on youtube seems invalid. Could you release or directly send me the links to download the video used in paper? I tried to download with the download_youtube.py and only download successfully with no more than 11w seconds, smaller than the 27hours described in the paper.

hello, you can use this link: https://www.dropbox.com/sh/k3k5iq0hg0y1mjm/AAAar3ObkFPkP4c87sDMggrta?dl=0
