### ISSUE TITLE
Running demo on custom video

### ISSUE THREAD

**Issue by sidk99** [yhw-yhw/SHOW#15]
It seems that stage 1 expects ground truth op values to run on a video, but also calculates the open pose values if they dont exist. 

However, in practice if there is no all.pkl in ```test/demo_video/ours``` , it does not detect any GT values and ends stage1 here https://github.com/yhw-yhw/SHOW/blob/06447d43f6f51c64cd62e4458765cfd364883c38/stage1_main.py#L218-L224

What steps do we need to run Show on a custom video from scratch?

**Comment by lithiumice** [comment]
> It seems that stage 1 expects ground truth op values to run on a video, but also calculates the open pose values if they dont exist.
> 
> However, in practice if there is no all.pkl in `test/demo_video/ours` , it does not detect any GT values and ends stage1 here
> 
> https://github.com/yhw-yhw/SHOW/blob/06447d43f6f51c64cd62e4458765cfd364883c38/stage1_main.py#L218-L224
> 
> What steps do we need to run Show on a custom video from scratch?

Can you check the log output of stage 1 that the Openpose worked correctly? There is a high probability that your Openpose is not installed properly

**Comment by mookerr** [comment]
Hello, I have the same problem, how did you solve it?

**Comment by vibhu-raturi** [comment]
Hello, anyone resolved this error?
