### ISSUE TITLE
Updated to run Colab for version 20230501

### ISSUE THREAD

**Issue by SlimeVRX** [yhw-yhw/SHOW#17]
Hi,

I just updated to run [Colab](https://colab.research.google.com/drive/1D7ZZyLDPnN1AiH0Y6xpX8oK3kUtkofM-?usp=sharing) for version 20230501

Thank for your work!

**Comment by lithiumice** [comment]
> Hi,
> 
> I just updated to run [Colab](https://colab.research.google.com/drive/1D7ZZyLDPnN1AiH0Y6xpX8oK3kUtkofM-?usp=sharing) for version 20230501
> 
> Thank for your work!

thanks for your excellent work!
