### ISSUE TITLE
Questions about differences between Paper and Code Implementation

### ISSUE THREAD

**Issue by LuckyOne09** [yhw-yhw/SHOW#18]
Thank you for your thorough and comprehensive work firstly! It is a very solid work. 
But I found some differences between paper and code default implementation.
For the default config, I found that:
1. You opted not to utilize the silhouette loss.
2. Instead of employing pymaf-x for hand pose initialization, you continued to use pixie hand pose initialization.
3. There was no utilization of mediapipe to generate additional keypoints for face mesh supervision.

I am interested in understanding the reasons behind these design choices and the insights behind them.
Thank you for your time and kindness!

**Comment by lithiumice** [comment]
3: using MediaPipe dose can often improve face mesh reconstruction quality. MediaPipe results will have a significant error if the video resolution is low. 1,2: silhouette loss and PyMaf-X are time-consuming, in the paper they should be opened, which is an omission of explanation.

**Comment by lithiumice** [comment]
yes. I will fix the config in code implementation later.

**Comment by LuckyOne09** [comment]
OK, thank you for your reply!
