### ISSUE TITLE
Inference on audio 

### ISSUE THREAD

**Issue by Siziff** [yhw-yhw/SHOW#19]
Good afternoon, maybe I was inattentive when I read the documentation, but how do I run your model on an audio file?

**Comment by SlimeVRX** [comment]
Please see the documentation in [TalkSHOW](https://github.com/yhw-yhw/TalkSHOW)

- This repo is SHOW: SHOW is processing data
- TalkSHOW is Generating Holistic 3D Human Motion from Speech

Thank you!
