### ISSUE TITLE
model.zip download fail

### ISSUE THREAD

**Issue by ggfresh** [yhw-yhw/SHOW#29]
Awesome work, when I execute "wget https://www.dropbox.com/s/gqdcu51ilo44k3i/models.zip?dl=0 -O models.zip" return 403：Forbidden

**Comment by ggfresh** [comment]
solved by a hard way

**Comment by ggfresh** [comment]
closed

**Comment by LeeBeen1** [comment]
Hi, can you give me some hints on how to fix this?
